# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ T286553-deploy ]
  pull_request:
    branches: [ T286553-deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm install
          npm run build
  
      - name: Preparing Demo
        run: ./scripts/demo.sh

      - name: Preparing Storybook
        run: npm run build-storybook

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            demo
            storybook-static

  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Unit Test (with coverage)
          run: npm run coverage
      
        - name: Cypress Test
          run: npm run dev & npm run cypress:run 

  deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Download Artifact
          uses: actions/download-artifact@v2
          with:
            name: artifact

        - name: Get branch name
          id: branch-name
          uses: tj-actions/branch-names@v5

        - name: Deploy Pages 🚀
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            branch: gh-pages-test # The branch the action should deploy to.
            folder: demo
            target-folder: ${{ steps.branch-name.outputs.current_branch }}

        - name: Deploy Storybook 🚀
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            branch: gh-pages-test # The branch the action should deploy to.
            folder: storybook-static
            target-folder: ${{ steps.branch-name.outputs.current_branch }}/storybook
